#https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
FROM node:8

EXPOSE 8000

# Create app directory
WORKDIR /usr/src/app

COPY . .
RUN npm install ./%%%HANDLERPATH%%%

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

CMD [ "node", "functionhandler.js" ]
