#https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
FROM node:8-alpine

EXPOSE 8000

# Create app directory
WORKDIR /usr/src/app

COPY . .
RUN npm install ./%%%HANDLERPATH%%%

CMD [ "node", "functionhandler.js" ]
