# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tinyfaas.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etinyfaas.proto\x12\x1eopenfogstack.tinyfaas.tinyfaas\"0\n\x04\x44\x61ta\x12\x1a\n\x12\x66unctionIdentifier\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2e\n\x08TinyFaaS\x12Y\n\x07Request\x12$.openfogstack.tinyfaas.tinyfaas.Data\x1a(.openfogstack.tinyfaas.tinyfaas.ResponseB\x0cZ\n.;tinyfaasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tinyfaas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n.;tinyfaas'
  _globals['_DATA']._serialized_start=50
  _globals['_DATA']._serialized_end=98
  _globals['_RESPONSE']._serialized_start=100
  _globals['_RESPONSE']._serialized_end=128
  _globals['_TINYFAAS']._serialized_start=130
  _globals['_TINYFAAS']._serialized_end=231
# @@protoc_insertion_point(module_scope)
