# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x19openfogstack.tinyfaas.api\"0\n\x04\x44\x61ta\x12\x1a\n\x12\x66unctionIdentifier\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2[\n\x08TinyFaaS\x12O\n\x07Request\x12\x1f.openfogstack.tinyfaas.api.Data\x1a#.openfogstack.tinyfaas.api.ResponseB\x07Z\x05.;apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005.;api'
  _DATA._serialized_start=40
  _DATA._serialized_end=88
  _RESPONSE._serialized_start=90
  _RESPONSE._serialized_end=118
  _TINYFAAS._serialized_start=120
  _TINYFAAS._serialized_end=211
# @@protoc_insertion_point(module_scope)
